"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
let car = 'subaru';
console.log("Is car == 'subaru'? I predict True.");
console.log(car == 'subaru');
let movie = 'Avengers';
console.log("Is movie == 'Avengers? I predict True.");
console.log(movie == 'Avengers');
let place = 'Japan';
console.log("Is place == 'Japan'? I predict True.");
console.log(place == 'Japan');
let Dessert = 'Cheese cake';
console.log("Is dessert == 'Cheese cake'? I predict True.");
console.log(Dessert == 'Cheese cake');
let Thing = 'Chair';
console.log("Is Thing == 'Chair'? I predict True.");
console.log(Thing == 'Chair');
console.log("\nFalse");
car = 'porche';
console.log("Is car == 'BMW'? I predict False.");
console.log(car == 'BMW');
movie = 'Barbie';
console.log("Is movie == 'oppenheimer'? I predict False.");
console.log(car == 'oppenheimer');
place = 'THailand';
console.log("Is place == 'Kuwait'? I predict False.");
console.log(place == 'Kuwait');
Dessert = 'ice cream';
console.log("Is Dessert == 'red velvet'? I predict False.");
console.log(Dessert == 'Red velvet');
Thing = 'Chair';
console.log("Is thing == 'cupboard'? I predict False.");
console.log(Thing == 'Cupboard');
